# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/nettensor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/nettensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15proto/nettensor.proto\"B\n\x0cSpikeRequest\x12\x0f\n\x07version\x18\x01 \x01(\x02\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x0e\n\x06spikes\x18\x08 \x01(\x0c\"i\n\rSpikeResponse\x12\x0f\n\x07version\x18\x01 \x01(\x02\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x10\n\x08\x63hild_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x07 \x01(\x0c\x12\x0e\n\x06spikes\x18\x08 \x01(\x0c\"y\n\x0cGradeRequest\x12\x0f\n\x07version\x18\x01 \x01(\x02\x12\x11\n\tsource_id\x18\x02 \x01(\t\x12\x11\n\tparent_id\x18\x04 \x01(\t\x12\x12\n\nmessage_id\x18\x07 \x01(\x0c\x12\x0e\n\x06spikes\x18\x08 \x01(\x0c\x12\x0e\n\x06grades\x18\t \x01(\x0c\"0\n\rGradeResponse\x12\x0f\n\x07version\x18\x01 \x01(\x02\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x02 \x01(\x08\x32_\n\tNetTensor\x12(\n\x05Spike\x12\r.SpikeRequest\x1a\x0e.SpikeResponse\"\x00\x12(\n\x05Grade\x12\r.GradeRequest\x1a\x0e.GradeResponse\"\x00\x62\x06proto3')
)




_SPIKEREQUEST = _descriptor.Descriptor(
  name='SpikeRequest',
  full_name='SpikeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='SpikeRequest.version', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='SpikeRequest.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spikes', full_name='SpikeRequest.spikes', index=2,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=91,
)


_SPIKERESPONSE = _descriptor.Descriptor(
  name='SpikeResponse',
  full_name='SpikeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='SpikeResponse.version', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='SpikeResponse.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='child_id', full_name='SpikeResponse.child_id', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='SpikeResponse.message_id', index=3,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spikes', full_name='SpikeResponse.spikes', index=4,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=198,
)


_GRADEREQUEST = _descriptor.Descriptor(
  name='GradeRequest',
  full_name='GradeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='GradeRequest.version', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_id', full_name='GradeRequest.source_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parent_id', full_name='GradeRequest.parent_id', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_id', full_name='GradeRequest.message_id', index=3,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spikes', full_name='GradeRequest.spikes', index=4,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grades', full_name='GradeRequest.grades', index=5,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=321,
)


_GRADERESPONSE = _descriptor.Descriptor(
  name='GradeResponse',
  full_name='GradeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='GradeResponse.version', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accept', full_name='GradeResponse.accept', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=371,
)

DESCRIPTOR.message_types_by_name['SpikeRequest'] = _SPIKEREQUEST
DESCRIPTOR.message_types_by_name['SpikeResponse'] = _SPIKERESPONSE
DESCRIPTOR.message_types_by_name['GradeRequest'] = _GRADEREQUEST
DESCRIPTOR.message_types_by_name['GradeResponse'] = _GRADERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SpikeRequest = _reflection.GeneratedProtocolMessageType('SpikeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SPIKEREQUEST,
  __module__ = 'proto.nettensor_pb2'
  # @@protoc_insertion_point(class_scope:SpikeRequest)
  ))
_sym_db.RegisterMessage(SpikeRequest)

SpikeResponse = _reflection.GeneratedProtocolMessageType('SpikeResponse', (_message.Message,), dict(
  DESCRIPTOR = _SPIKERESPONSE,
  __module__ = 'proto.nettensor_pb2'
  # @@protoc_insertion_point(class_scope:SpikeResponse)
  ))
_sym_db.RegisterMessage(SpikeResponse)

GradeRequest = _reflection.GeneratedProtocolMessageType('GradeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GRADEREQUEST,
  __module__ = 'proto.nettensor_pb2'
  # @@protoc_insertion_point(class_scope:GradeRequest)
  ))
_sym_db.RegisterMessage(GradeRequest)

GradeResponse = _reflection.GeneratedProtocolMessageType('GradeResponse', (_message.Message,), dict(
  DESCRIPTOR = _GRADERESPONSE,
  __module__ = 'proto.nettensor_pb2'
  # @@protoc_insertion_point(class_scope:GradeResponse)
  ))
_sym_db.RegisterMessage(GradeResponse)



_NETTENSOR = _descriptor.ServiceDescriptor(
  name='NetTensor',
  full_name='NetTensor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=373,
  serialized_end=468,
  methods=[
  _descriptor.MethodDescriptor(
    name='Spike',
    full_name='NetTensor.Spike',
    index=0,
    containing_service=None,
    input_type=_SPIKEREQUEST,
    output_type=_SPIKERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Grade',
    full_name='NetTensor.Grade',
    index=1,
    containing_service=None,
    input_type=_GRADEREQUEST,
    output_type=_GRADERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETTENSOR)

DESCRIPTOR.services_by_name['NetTensor'] = _NETTENSOR

# @@protoc_insertion_point(module_scope)
